### PR TITLE
update layer0 version numbers

### PR DESCRIPTION
**Pull request by Steve-B-Murphy**

### CODE REVIEW

**Comment by Steve-B-Murphy** [comment]
Please verify

**Comment by tristanlee85** [comment]
@Steve-B-Murphy this should use `0 use latest` and commit the lock file.

**Comment by Steve-B-Murphy** [comment]
@tristanlee85 
For the lock file do I change the version number in both "`version`" and the tgz file? Example:"@layer0/cli": {
```
      "version": "3.6.0",
      "resolved": "https://registry.npmjs.org/@layer0/cli/-/cli-3.6.0.tgz",
```

`0 use latest` - do you mean add this to the readme?

**Comment by Steve-B-Murphy** [comment]
@tristanlee85 I updated using `0 use latest` as you requested.

**Pull request merged**
